### ISSUE TITLE
shen.fbound? doesn't work for primitive and lang implementation (shen.*) functions

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-sources#19]
`fbound?` relies on a function having an entry in `(get Name source)`, according to the source of the `fbound?` and `ps` functions.

Here's an excerpt from a REPL session I just had.

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 19.2
running under Common Lisp, implementation: CLisp
port 1.9 ported by Mark Tarver

(5-) (shen.fbound? map)
false

(6-) (shen.fbound? +)
false

(7-) (define xor X Y -> (and (or X Y) (not (and X Y))))
xor

(8-) (shen.fbound? xor)
true

(9-) (get xor source)
value not found


(10-) (ps xor)
[defun xor [V1163 V1164] [and [or V1163 V1164] [not [and V1163 V1164]]]]

(11-) (ps +)
+ not found.


(12-) (ps map)
map not found.
```

Seems like it should return true for any symbol that has a global function that can be applied.

Expected:

```
(0-) (shen.fbound? +)
true

(1-) (shen.fbound? map)
true

(2-) (define xor X Y -> (and (or X Y) (not (and X Y))))
xor

(3-) (shen.fbound? xor)
true
```

Perhaps the shen sources could pre-populate the source property for all these with the actual source for lang implementation functions (functions defined in shen-sources) and some placeholder for primitives. Or a placeholder for all as some of the shen.* functions might be implemented as native functions, depending on port. That way, `fbound?` would return true.

If we decide on a solution, I can put together a pull request.

**Comment by deech** [comment]
I've run into this case before not just for primitives but for functions I've re-implemented in the target language for efficiency. Even the SBCL version has this issue. 

I think we should be pre-populating the global property vector with primitives and peep-hole optimized functions so `shen.fbound?` returns `true`. What about a symbol like `<primitive>` as the return value for `(ps ...)`? Slightly more ambitious is a string containing the source in the target language. Even more ambitious is pre-made FFI call so it can actually be run in the REPL. :)

**Comment by tizoc** [comment]
It is ok that way, consider that `shen.fbound?` is there only for internal use (to know if a value has a printer), and for nothing else.

Another issue with storing the source for all Shen internal functions is that any of those functions can be overriden by the port using its own native code, and because of that the result of `ps` in such cases would not be correct. There are ways around this but I don't think it warrants the added complexity.

But related to this, I think the Shen->KLambda compiler could output more information in the form of KLambda code, because some is lost right now (the obvious thing being type information, it would be nice to output `(declare ...)` calls for example).

**Comment by tizoc** [comment]
@rkoeninger @deech is asking if a global function is bound an operation you use often? it is not something I usually do (in either Shen or any language).

All my previous reasoning is based on `shen.fbound?` being something that is there for internal use (and for its intended use it does his job well). It is an implementation detail and not something exposed to users.

`ps` is exposed, but my interpretation is that its main reason to exists is so that stuff like `track`/`untrack` works, and thats why the not-so-readable Kl code is stored there instead of the much more friendly Shen code.

**Comment by rkoeninger** [comment]
@tizoc I saw `fbound?` mentioned in the spec and tried it out and it wasn't working for any of the pre-defined functions. It hasn't actually given me any trouble, but I thought I'd bring it up and offer to work on the fix.

If you think it's not significant, then we can just close this issue. Maybe make a note of this in the source next to the define of `fbound?`.

**Comment by tizoc** [comment]
> If you think it's not significant, then we can just close this issue. Maybe make a note of this in the source next to the define of fbound?.

That sounds good to me. I just think that fixing it adds a bigger cost than benefit.

Considering that right now it is only used for print-vectors, and that the implementation of print-vectors is kinda hacky right now, I think it would be more productive to improve that, than to adapt stuff to keep supporting something hacky.

To understand what I mean, see: https://github.com/Shen-Language/shen-sources/blob/89e08b8d5987f8d48f475432c8c112a2f731e3b4/sources/writer.shen#L120-L133

To know if a vector is printable, Shen checks if it is an absvector, then it obtains the first element, and if is a symbol, it checks if a function with that name is bound with `shen.fbound?`, if so, then that function is assumed to be the function that can convert this vector into a string. For example, if you use a vector to represent a "date" object, you would use an absvector with element 0 being the symbol "date". Whenever Shen had the need to convert it into a string it would use the "date" function (if bound) to do so. I don't know about others, but this is a coupling that I don't like much.

Another important detail is that both `ps` (and because of that `shen.fbound?`) only work when loading typing code in the repl or using `load` to compile it, because it is the Shen reader who takes care of attaching the KLambda code to the named function. If you were to write a pre-compiler so that your programs loaded (or even ran) faster by pre-generating and pre-compiling code in your port's native language, you would find that while it is running you don't have access to the results of `ps` unless you explicitly associate each function's code at runtime, kinda like what happens with all primitives and Shen's internal code).

The clean solutions that I can think of (either declaring printers explicitly with something like `(declare-printer date (function show-date))`, or use a more elaborated datatype for element 0 in such custom types, so that the printer is directly available there) are not exactly backwards compatible. Maybe the best thing would be to implement one of such options while still keeping the current behavior.

/ramble ends here
:)

**Comment by tizoc** [comment]
@rkoeninger I come with an alternative implementation that while not perfect, is in my opinion better than the current one and solves your problem without requiring any extra bookkeeping at runtime that is not already there:

```shen

(package shen []

(define fbound?
  F -> (trap-error
        (do (lookup-func F (value *symbol-table*)) true)
        (/. E false)))
)
```

example:

```
(1-) (package shen []

(define fbound?
  F -> (trap-error
        (do (lookup-func F (value *symbol-table*)) true)
        (/. E false)))
)
shen.fbound?

(2-) (shen.fbound? map)
true

(3-) (shen.fbound? unknown)
false
```

What do you think?

**Comment by rkoeninger** [comment]
So if the `function` function works on it, it's a function.

Makes sense.

And that seems to work for primitives, functions from lang sources (excluding shen.*) and repl/loaded functions.

It still seems odd to me that `(shen.fbound? shen.mod)` would return false. It would help to have a function that lets you know if a function (for any function) exists. Like there would be a 1-to-1 relationship between symbols `fbound?` returns true for and symbols that represent global functions. But that might not be a priority.

**Comment by tizoc** [comment]
> @tizoc So if the function function works on it, it's a function.

Exactly. Every time a function is defined, it is added to the lookup table, but this happens at the Shen level (that is, it is the reader who takes care of this, not the KLamda evaluator), and because of this the functions that already come in Shen are not all registered (and the ones who are, get registered manually here: https://github.com/Shen-Language/shen-sources/blob/89e08b8d5987f8d48f475432c8c112a2f731e3b4/sources/declarations.shen#L188-L193

As you can see, only Shen external functions are registered.

But yeah I would not say this is high priority (again, cost/benefit) being that `shen.fbound?` is an internal function, and not part of Shen's interface. Btw, in which spec did you see it mentioned? I couldn't find it in Shen's 19.2 spec.

Btw if you think the implementation I provided is good enough feel free to make a PR for reviewing.

**Comment by rkoeninger** [comment]
I saw `fbound?` in the [porting document](https://github.com/Shen-Language/shen-sources/blob/master/specification/porting.htm).

> ...In general single and dual namespace languages are observationally equivalent as long as the space of function identifiers and global identifiers are kept disjoint. Such a regime is easily maintained in 99% of all cases by simply checking to see if the identifier is bound to a function (**fbound?** function test in Shen) if it is to be used as a global or a global (bound? function test in Shen) if used as a function and issuing an error if this is the case...

Hmmm... so now I'm experimenting with the `bound?` function and in my port it does not return true for functions (like `(bound? +)`), which I think is the right behavior, but in the SBCL port is does.

Which one is right? File a separate bug?

**Comment by tizoc** [comment]
@rkoeninger `bound?` is different, it is not for functions, it is for global variables (thats why `fbound?` has an `f` as a first letter, because it is for **f**unctions)

Let me check in my sbcl install, because it shouldn't be returning true for `+`.

**Comment by tizoc** [comment]
@rkoeninger the Common Lisp port has an empty list associated to `+`, but I have no idea why.

Here is the definition of `bound?` btw:

https://github.com/Shen-Language/shen-sources/blob/89e08b8d5987f8d48f475432c8c112a2f731e3b4/sources/sys.shen#L461-L466

**Comment by tizoc** [comment]
````
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 19.2
running under Common Lisp, implementation: SBCL
port 1.9 ported by Mark Tarver


(0-) (bound? +)
true

(1-) (bound? -)
true

(2-) (bound? map)
false

(3-) (bound? cd)
false

(4-) (bound? append)
false
```

**Comment by tizoc** [comment]
Ok, I figured out why, it is related to Common Lisp's dual namespace. If something is already defined as a function, you will not get an undefined variable error by referencing it, but the associated value will be NIL (the empty list).

The CL port implements `value` as:

`(DEFUN value (X) (SYMBOL-VALUE X))`

I guess the way the CL port uses to disambiguate regular symbols doesn't work for non alphanumeric ones like `+`, `-`, `/`, etc.

**Comment by rkoeninger** [comment]
The `bound?` function being unrelated, I think #21 fixes the problem and this can be closed,
