### ISSUE TITLE
Typo in make.shen

### ISSUE THREAD

**Issue by sirikid** [Shen-Language/shen-sources#70]
Shouldn't it be `fold-right`?
https://github.com/Shen-Language/shen-sources/blob/f26d3e7959773faf316c7870055d8264f65be902/make.shen#L29

**Comment by rkoeninger** [comment]
Yes, it should have been `fold-right`, but considering that and other functions were [removed in 21.0](https://github.com/Shen-Language/shen-sources/blob/f26d3e7959773faf316c7870055d8264f65be902/CHANGELOG.md#removed), `fold-righ` and other entries could be removed from `make.shen`. (Also need to double-check `declarations.shen` maybe?)

**Comment by tizoc** [comment]
@rkoeninger no, I think you are correct, thats not necessary. It's only purpose is to help ports still running an older version of the kernel to recompile the Shen files to get the new kernel (something that is not strictly needed because we provide klambda sources in the release too, but it is useful if the porter wants to make changes to the `.shen` files and test them).
