### ISSUE TITLE
Add a new document with instructions on how to update to new releases

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#86]
Some times new releases require changes in ports, document that in `doc/port-upgrades.md`

**Comment by rkoeninger** [comment]
What's the relationship between this document and the changelog? Would the port upgrades have a section for each release and what breaking change or optimization opportunities there are? Does it elaborate on the details of the changelog and offer more information on how to respond to those changes or is it highlights from the changelog?

**Comment by tizoc** [comment]
> Would the port upgrades have a section for each release and what breaking change or optimization opportunities there are?

Exactly this. Changelog contains brief descriptions of the changes, but I feel more in depth explanations don't fit there because they can get too long.

**Comment by rkoeninger** [comment]
Cool. I can take a shot at writing this unless you're already planning on doing so.

Maybe I should also try to redo the porting doc since it's just a copy of the one from shenlanguage.org and is a little confusing. I think it's referencing a work process where you download a zip file from the website, extract, add code for your port, and then email it back. We don't do it that way anymore.

Also, the links in the shendoc and system functions docs are broken. Having a document that just has a link is strange - could those just be links in the readme?

I also think the wiki is of limited use. External sources of information fall out of sync very easily, especially when they're controlled by someone other than who's working on the kernel. Even the open source site has this problem, it was painful to update the current version to 21.2 and see the whole grid go yellow.

**Comment by tizoc** [comment]
@rkoeninger if you feel like doing so, then yes please!

I'm almost sure that for previous versions that had breaking changes or extra optimization opportunities I wrote some instructions in the release announcement email I sent to the list, you can search for those if you want to save a bit of time.

Re: docs with links, those used to be full docs, but had to be removed (I don't remember if Mark asked for them to not be duplicated in re repo or why). Just found the system functions doc here http://www.shenlanguage.org/system.pdf, I would leave that one document in the repo-as is but with the fixed link, because it includes a few extra functions that are not mentioned there, and I see no other good place to put that. 

Agree regarding the `shendoc` one, lets get rid of it and just put the link on the README.
Not sure about the wiki thing (linked in performance doc), but I guess the documentation there can just be added to the repository, I think back then it didn't feel right putting in an unfinished document.
